# Generated by Django 4.0.8 on 2023-01-04 14:00

import api.models.user.author
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('avatar', stdimage.models.StdImageField(blank=True, null=True, upload_to=api.models.user.author.get_author_avatar_image_path, verbose_name='Author avatar')),
                ('nickname', models.CharField(help_text='The nickname of the author', max_length=64)),
                ('fio', models.CharField(default='', help_text='Fio of the author', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('nickname',), name='unique_constraint_for_author'),
        ),
        migrations.AddField(
            model_name='user',
            name='author_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='api.author', verbose_name='Information about the author if it exists'),
        ),
    ]
