# Generated by Django 4.0.8 on 2023-03-01 12:34

import api.models.project.project
import api.models.project.project_file_data
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_author_unique_constraint_for_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('title', models.CharField(help_text='The title project', max_length=256)),
                ('type_data', models.CharField(choices=[('file', 'File'), ('symbol', 'Symbol Yahoo')], help_text='The type data project', max_length=56)),
                ('project_cover', stdimage.models.StdImageField(blank=True, null=True, upload_to=api.models.project.project.get_project_cover_image_path, verbose_name='AProject cover')),
                ('project_status', models.CharField(choices=[('draft', 'Draft'), ('in_work', 'In work'), ('ready', 'Ready')], help_text='Project current status', max_length=56)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.project.project_file_data.get_project_file_data_path)),
            ],
            options={
                'verbose_name_plural': 'ProjectFileData',
            },
        ),
        migrations.CreateModel(
            name='YahooSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('symbol', models.CharField(help_text='Symbol company Yahoo', max_length=126)),
                ('name', models.CharField(help_text='Name company from Yahoo', max_length=512)),
            ],
            options={
                'verbose_name_plural': 'YahooSymbol',
            },
        ),
        migrations.CreateModel(
            name='YahooSymbolsCsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('file', models.FileField(default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Yahoo Symbol Csv Import',
                'verbose_name_plural': 'Yahoo Symbols Csv Import',
            },
        ),
        migrations.AddConstraint(
            model_name='yahoosymbol',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_constraint_for_yahoo_symbol'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file_data',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.PROTECT, to='api.projectfiledata'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.yahoosymbol'),
        ),
    ]
