# Generated by Django 4.0.8 on 2023-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_projectfiledata_yahoosymbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('draft', 'draft'), ('in_work', 'in work'), ('ready', 'ready')], help_text='Project current status', max_length=56),
        ),
    ]
