# Generated by Django 4.0.8 on 2023-04-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_projectmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='save_model_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
