# Generated by Django 4.0.8 on 2023-04-22 10:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_projectmodel_save_model_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update time')),
                ('predictions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('mae', models.IntegerField(blank=True, null=True)),
                ('r2', models.IntegerField(blank=True, null=True)),
                ('mape', models.IntegerField(blank=True, null=True)),
                ('rmse', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.project')),
                ('project_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.projectmodel')),
            ],
            options={
                'verbose_name_plural': 'ProjectResultData',
            },
        ),
    ]
