# Generated by Django 4.0.8 on 2023-05-07 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_projectresult_mae_alter_projectresult_mape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresult',
            name='loss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='mae_train',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='mape_train',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='predictions_year',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='r2_train',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='rmse_train',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectresult',
            name='val_loss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
