# Generated by Django 4.0.8 on 2023-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_projectresult_loss_projectresult_mae_train_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='indicator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='model',
            field=models.CharField(blank=True, choices=[('lstm', 'lstm'), ('cnnLstm', 'cnnLstm'), ('cnnBiLstm', 'cnnBiLstm')], max_length=64, null=True),
        ),
    ]
